# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_suap', models.URLField(max_length=255, verbose_name='URL da API do SUAP')),
                ('usuario_suap', models.CharField(max_length=255, verbose_name='Usu\xe1rio do SUAP')),
                ('senha_suap', models.CharField(max_length=255, verbose_name='Senha do SUAP')),
                ('url_ckan', models.URLField(max_length=255, verbose_name='URL da API do CKAN')),
                ('token_ckan', models.CharField(max_length=255, verbose_name='Token de Autentica\xe7\xe3o do CKAN')),
                ('nome_mantenedor', models.CharField(max_length=60)),
                ('email_mantenedor', models.EmailField(max_length=60)),
            ],
            options={
                'verbose_name': 'Configura\xe7\xe3o do Sistema',
                'verbose_name_plural': 'Configura\xe7\xf5es do Sistema',
            },
        ),
    ]
