# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20170427_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjuntoDeDados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, verbose_name='T\xedtulo')),
                ('descricao', models.TextField(verbose_name='Descri\xe7\xe3o')),
                ('slug', models.SlugField(max_length=80, verbose_name='Slug')),
                ('url_endpoint', models.URLField(verbose_name='URL do Endpoint no SUAP')),
                ('etiquetas', models.CharField(max_length=80, verbose_name='Etiquetas')),
            ],
            options={
                'verbose_name': 'Conjunto de Dados',
                'verbose_name_plural': 'Conjuntos de Dados',
            },
        ),
    ]
