# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_conjuntodedados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosistema',
            name='url_suap',
            field=models.URLField(max_length=255, verbose_name='URL do SUAP'),
        ),
        migrations.AlterField(
            model_name='conjuntodedados',
            name='etiquetas',
            field=models.CharField(help_text='Informe as etiquetas separadas por v\xedrgula. Exemplo: "ensino, pesquisa, extens\xe3o"', max_length=80, verbose_name='Etiquetas'),
        ),
    ]
