# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20170429_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjuntodedados',
            name='horario_extracao',
            field=models.TimeField(default='00:00', verbose_name='Hor\xe1rio de Execu\xe7\xe3o da Extra\xe7\xe3o'),
        ),
        migrations.AddField(
            model_name='conjuntodedados',
            name='periodicidade_extracao',
            field=models.PositiveIntegerField(choices=[(1, 'Di\xe1ria'), (2, 'Semanal'), (3, 'Mensal'), (4, 'Semestral'), (5, 'Anual')], default=2, verbose_name='Periodicidade'),
        ),
        migrations.AlterField(
            model_name='conjuntodedados',
            name='url_endpoint',
            field=models.URLField(verbose_name='URL do Endpoint na API do SUAP'),
        ),
    ]
