# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20170429_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroExtracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_horario_inicio_extracao', models.DateTimeField(verbose_name='Data e Hor\xe1rio de In\xedcio da Extra\xe7\xe3o')),
                ('data_horario_termino_extracao', models.DateTimeField(verbose_name='Data e Hor\xe1rio de T\xe9rmino da Extra\xe7\xe3o')),
                ('quantidade_registros', models.PositiveIntegerField(verbose_name='Quantidade de Registros Extra\xeddos')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Falha'), (2, 'Sucesso')], verbose_name='Status')),
                ('conjunto_dados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ConjuntoDeDados', verbose_name='Conjunto de Dados')),
            ],
            options={
                'verbose_name': 'Registro de Extra\xe7\xe3o de Dados',
                'verbose_name_plural': 'Registros de Extra\xe7\xe3o de Dados',
            },
        ),
    ]
