# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_registroextracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Exemplo: Instituto Federal do Rio Grande do Norte', max_length=80, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descri\xe7\xe3o')),
                ('slug', models.SlugField(max_length=80, verbose_name='Slug')),
                ('url_logomarca', models.URLField(verbose_name='URL da Logomarca')),
            ],
            options={
                'verbose_name': 'Organiza\xe7\xe3o',
                'verbose_name_plural': 'Organiza\xe7\xf5es',
            },
        ),
    ]
