# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20170501_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjuntodedados',
            name='id_ckan',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='ID no CKAN'),
        ),
    ]
