# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_conjuntodedados_id_ckan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Exemplo: Ensino', max_length=80, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descri\xe7\xe3o')),
                ('slug', models.SlugField(max_length=80, verbose_name='Slug')),
                ('url_imagem', models.URLField(verbose_name='URL da Imagem')),
                ('id_ckan', models.CharField(blank=True, max_length=80, null=True, verbose_name='ID no CKAN')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
    ]
