# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_conjuntodedados_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjuntodedados',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='url_imagem',
            field=models.URLField(blank=True, null=True, verbose_name='URL da Imagem'),
        ),
        migrations.AlterField(
            model_name='organizacao',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='organizacao',
            name='url_logomarca',
            field=models.URLField(blank=True, null=True, verbose_name='URL da Logomarca'),
        ),
    ]
